apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-3
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: app-of-apps
  project: default
  source:
    path: app-of-apps/my-app-3
    repoURL: https://github.com/allir/argo-cd-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
