apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-3
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: test-apps
  project: default
  source:
    path: my-app-3
    repoURL: https://github.com/allir/argo-cd-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
