apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app-3
  name: my-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app-3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
