apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-app-3
  name: my-app-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app-3
  type: ClusterIP
status:
  loadBalancer: {}
