apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
    appnumber: "1"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: app-1
        appnumber: "1"
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
