apiVersion: v2
name: mychart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: subchart1
  - name: subchart2
  - name: subchart3
  - name: subchart4
  - name: subchart5
  - name: subchart6
  - name: subchart7
  - name: subchart8
  - name: subchart9
  - name: subchart10
  - name: allisub
    condition: alli.enabled, allisub.enabled
    tags:
      - alli
      - allisub
  - name: mysubchart
    version: ~0.1.0
    repository: "file://../mysubchart"
    condition: mysubchart.enabled
  - name: mysubchart2
    version: ~0.1.0
    repository: "file://../mysubchart2"
    condition: mysubchart2.enabled
  - name: mysubchart3
    version: ~0.1.0
    repository: "file://../mysubchart3"
    condition: mysubchart3.enabled
  - name: extra1
    version: ~0.1.0
    repository: "file://../extra1"
    condition: extra1.enabled
    tags:
      - extras
  - name: extra2
    version: ~0.1.0
    repository: "file://../extra2"
    condition: extra2.enabled
    tags:
      - extras
  - name: extra3
    version: ~0.1.0
    repository: "file://../extra3"
    condition: extra3.enabled
    tags:
      - extras
