apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    appnumber: "2"
  name: app-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-2
  type: ClusterIP
