{{- if .Values.global.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  dessert: {{ .Values.dessert | b64enc }}
  salad: {{ .Values.global.salad | b64enc }}
{{- end -}}
