apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-of-apps-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: waves-of-apps
  project: default
  source:
    path: waves-of-apps/my-app-2
    repoURL: https://github.com/allir/argo-cd-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
