apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-2
    appnumber: "2"
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  strategy: {}
  template:
    metadata:
      labels:
        app: app-2
        appnumber: "2"
    spec:
      initContainers:
        - name: sleep
          image: busybox
          command:
          - 'sh'
          - '-c'
          - "sleep 120"
      containers:
      - image: nginx
        name: nginx
        resources: {}
