apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-3
    appnumber: "3"
  name: app-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-3
  type: ClusterIP
