apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
  {{- template "mychart.labels" $ }}
  {{- include "mychart.app" $ | nindent 4 }}
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{ with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- if eq .drink "coffee" -}}
  {{- nindent 2 "mug: 'true'" }}
  {{- end }}
  release: {{ $relname }}
  {{- include "mychart.app" $ | nindent 2 }}
  {{- end }}
  salad: {{ .Values.global.salad }}
