{{- if .Values.global.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  {{- template "mychart.labels" $ }}
  {{- include "mychart.app" $ | nindent 4 }}
data:
  myvalue: {{ "Hello World" | b64enc }}
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote | b64enc}}
  food: {{ .food | upper | quote | b64enc }}
  release: {{ $relname | quote | b64enc }}
  {{- include "mychart.app" $ | nindent 2 | b64enc }}
  {{- end }}
  salad: {{ .Values.global.salad | quote | b64enc }}
{{- end -}}
